### ISSUE TITLE
凯子哥的勘误表

### ISSUE THREAD

**Issue by ZhaoKaiQiang** [bboyfeiyu/dp-issues#1]
下面的勘误将采用以下的格式：页码-(上/中/下)行数-错误原因。上/中/下，代表从位置
1. 2-下7-少空格
2. 13-上18-“无线”应为“无限”
3. 17-下7-多空格
4. 18-上17-“飞越”应为“飞跃”
5. 19-下-Tenant类中的roomArea、roomPrice未初始化，也未赋值，不知道干嘛用
6. 21-上-同上
7. 22-上-14-“rul”应为“LRU”
8. 26-下-“CheckLock”应为“Check Lock”
9. 27-中-“调整了JVM、具体化了“，中间的、应为，
10. 28-下-Objectinstance中间应该有空格，
11. 28-下-没看明白Singleton的构造函数怎么出现在了这里
12. 29-上-ObjectService中间应该有空格
13. 44-中-“且组装顺序确实不固定的”不通顺，应为“并且组装顺序是不固定的“
14. 44-上1-“组件”应为“组建”
15. 48-中-排版乱
16. 50-上-排版乱
17. 52-上-if(mListView!=null){}的18. 括号多一个}
18. 55-排版乱
19. 55-中-"meature"应为“measure”
20. 55-下6-“但并不是只有UI线程才能更新线程”应为“但并不是因为只有UI线程才能更新UI”
21. 62-上-真是“山重水复疑无路，柳暗花明又一村。”的句号应该放在引号外面，因为诗句是组成这句话的一部分，不能单独成句
22. 63-下-排版乱
23. 64-上-“字段私有优化”应为“字段私有化”

后面还没读，发现了再发~

**Comment by hehonghui** [comment]
好多呀~ 有的问题是由于Mac版word的问题造成的，mac版word极不好用。谢啦，凯子
